### ISSUE TITLE
Lua API Changes Proposal

### ISSUE THREAD

**Issue by Lucky4Luuk** [Lucky4Luuk/beammp_rust_server#15]
# Lua API Changes Proposal
Notes on how to read this:
- If the final argument is ... , it means it should take variadic arguments

## Events
- Remove `MP.CreateEventTimer` (and `MP.CancelEventTimer`)
- Add `MP.ScheduleEvent("EventName", TimeInMillis, ...)`
- Change `MP.TriggerGlobalEvent` to take variadic arguments the same way `MP.TriggerLocalEvent` does. Currently, it is a bit of a pain to use this function!
- Ensure `MP.TriggerClientEvent` can also take no data! In the future, I'd like to see it also take arbitrary events, but I think this is much harder to expect unless the client can automatically decode a certain format we decide upon and give you the right arguments again.
- Remove `MP.Sleep`. It sucks.

## FS
Currently, the filesystem functions are great, they are nice features to have.
My only complaint is that it is a bit weird sometimes to mix the `FS` calls and `io` calls.
Not sure what I want to see changed here, but perhaps expanding it to cover most `io` usecases would be nice.
That way, it also wouldn't be confusing to deal with paths between the 2. Not sure if that is currently a problem, but I think it's confusing to mix the 2 still.

## Other
- Add `MP.Get("Category", "Setting")` to get any settings from the server config.
- Change `MP.Set` to `MP.Set("Category", "Setting", value)`. This is much more intuitive.
- Change the behaviour of loading the config, so it doesn't strip unused values, so mods can write/read their own values in the main config.
- Add a config flag or cli argument to prevent `MP.Set` overwriting the max players value.

## API Additions
- Add a command framework for the chat. Many plugins use chat commands, but I feel like everyone always ends up reinventing the wheel. A unified system with permissions could lead to some very nice possible additions, like /help but also properly informing the player if a command is unknown.
- Support banning players natively, with something like `MP.BanPlayer(BeamMpId)` and `MP.UnbanPlayer(BeamMpId)`.
- Add an HTTP(S) module, to make it significantly easier for plugins to make GET/POST requests.
- Add a websockets module.
- (IN CASE CLIENT CHANGES ARE FINE TOO) Add a few default events that the server can trigger in the client, so we can streamline the process of modifying the client from the server. Perhaps a way to do everything from adding UI to teleporting the car to forcing a specific car?

**Comment by 20dka** [comment]
About comments: I think CobaltEssentials implements a nice interface, we could implement something similar in Rust

**Comment by Lucky4Luuk** [comment]
Sure. How would you see the CE command framework implemented in the official API? We can't really just rip CE 100%, so if you could write down some of the functions that we'd need and how you'd like them to work, that be nice!

**Comment by Starystars67** [comment]
I wonder could a `MP.Timeout` be useful? E.g. to run something only once rather than a scheduled event.

Also regarding the following point:
> Support banning players natively, with something like MP.BanPlayer(BeamMpId) and MP.UnbanPlayer(BeamMpId).

Could this be adjusted instead to take one of 2 options, Either the players ID in the session (though could be problematic)
Or instead any string option so it can be used to also IP ban if so desired?

**Comment by Lucky4Luuk** [comment]
> I wonder could a MP.Timeout be useful? E.g. to run something only once rather than a scheduled event.

That's the point of the scheduling, it only runs it in x ms and never again. You have to keep requesting it to be scheduled, instead of a timer constantly triggering it.

> Could this be adjusted instead to take one of 2 options, Either the players ID in the session (though could be problematic)
Or instead any string option so it can be used to also IP ban if so desired?

I think it'd be better to have MP.BanIP and MP.UnbanIP for more clarity.

**Comment by Lucky4Luuk** [comment]
Closing, repo has moved to the official BeamMP server repo.
